routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\PostController;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/category', 'CategoryController');
Route::resource('/tag', 'TagController');
Route::get('/post/hapus', 'PostController@list_postdelete')->name('list_postdelete');
Route::get('/post/restore{id} ', 'PostController@restore')->name('post.restore');
route::delete('/post/Kill{id}', 'PostController@kill')->name('post.kill');
Route::resource('post','PostController');

Route::get('/dashboard', function(){
    return view('admin.master');
})->name('dashboard');

app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Posts extends Model
{
    use SoftDeletes;

    protected $date = ['delete_at'];
    protected $fillable = ['judul','category_id','content','gambar','slug'];

    public function category(){
        return $this->BelongsTo('App\Category');
    }

    public function tags(){
        return $this->belongsToMany('App\Tags');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\Posts;
use App\Category;
use App\Tags;
use Illuminate\Support\Str;

use Illuminate\Http\Request;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = Posts::paginate(10);
        return view('post.index', compact('post'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tags::all();
        $category = Category::all();
        return view('post.create', compact('category','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
           'judul' => 'required ',
           'category_id' =>  'required',
           'content' => 'required',
           'gambar' => 'required'
        ]);

        $gambar = $request->gambar;
        // menghindari redudansi data :  Unik nama gambar
        $nama_gambar = time().$gambar->getClientOriginalName();

        $post = Posts::create([
           'judul' => $request->judul,
           'category_id' =>  $request->category_id,
           'content' => $request->content,
           'gambar' =>  'public/uploads/posts/'.$nama_gambar,
           'slug' => Str::slug($request->judul)
        ]);
            //penyimpanan multiple select : tags
            $post->tags()->attach($request->tags);
            //lokasi penyimpanan file gambar
            $gambar->move('public/uploads/posts/', $nama_gambar);
            return redirect()->route('post.index')->with('success', 'Postingan anda berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::all();
        $tags = Tags::all();
        $post = Posts::findorfail($id);
        return view('post.editpost', compact('post','tags','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'judul' => 'required',
            'category_id' => 'required',
            'content' => 'required'
         ]);

        $post = Posts::findorfail($id);

        //jika terdapat gambar disertakan
        if ($request->hasFile('gambar')) {
            $gambar = $request->gambar;
            $nama_gambar = time().$gambar->getClientOriginalName();
            $gambar->move('public/uploads/posts/', $nama_gambar);

        $post_data = [
            'judul' => $request->judul,
            'category_id' =>  $request->category_id,
            'content' =>  $request->content,
            'gambar' => 'public/uploads/posts/'.$nama_gambar,
            'slug' => Str::slug($request->judul)
        ];
        }


        //jika tidak terdapat gambar disertakan
        else{
        $post_data = [
            'judul' => $request->judul,
            'category_id' =>  $request->category_id,
            'content' =>  $request->content,
            'slug' => Str::slug($request->judul)
        ];
        }

        $post->tags()->sync($request->tags);
        $post->update($post_data);

        return redirect()->route('post.index')->with('success','Postingan anda berhasil diupdate');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Posts::findorfail($id);
        $post->delete();
        return redirect()->back()->with('success', 'Postingan berhasil di delete');

    }

    public function list_postdelete(){
        $postdelete  = Posts::onlyTrashed()->paginate(10);
        return view ('post.deletepost', compact('postdelete'));
    }

    public function restore($id){
        $post_restore = Posts::withTrashed()->where('id', $id)->first();
        $post_restore->restore();
        return redirect()->back()->with('success','Postingan berhasil di Restore');
    }

    public function kill($id){
        $post_kill = Posts::withTrashed()->where('id', $id)->first();
        $post_kill->forceDelete();

        return redirect()->back()->with('success', 'Postingan berhasil dihapus Permanen');



    }
}

resources/views/post/create.blade.php
@extends('admin.master')
@section('content')
@section('Judul-Page','Create POST')

@if (count($errors)>0)
    @foreach($errors->all() as $error)
    <div class="alert alert-danger" role="alert">
    {{$error}}
    </div>
    @endforeach
@endif

@if(Session::has('success'))
<div class="alert alert-success" role="alert">
   {{Session('success')}}
   </div>
@endif

<form action="{{route('post.store')}}" method="POST" enctype="multipart/form-data">
@csrf
<div class="form-group">
    <label for="">Judul</label>
    <input type="text" class="form-control" name="judul">
</div>

<div class="form-group">
    <label for="">Kategori</label>
    <select class="form-control" name=category_id>
    <option value="">Pilih Category</option>
    @foreach($category as $hasil)
        <option value="{{$hasil->id}}">{{$hasil->nama}}</option>
    @endforeach
    </select>
</div>


<div class="form-group">
    <label for="">Pilih Tag</label>
    <select class="form-control select2" multiple=""  name="tags[]">
        @foreach ($tags as $tag)
        <option value="{{$tag->id}}">{{$tag->nama}}</option>
        @endforeach
    </select>
</div>


<div class="form-group">
    <label for="">Isi Content</label>
    <input type="text" class="form-control" name="content">
</div>

<div class="form-group">
    <label for="">Thumbnail</label>
    <input type="file" class="form-control" name="gambar">
</div>
<div class="form-group">
    <button class="btn btn-primary btn-block">SIMPAN</button>
</div>
</form>

<a href="{{route('post.index')}}" class="btn btn-success">Kembali</a>


@endsection

resources/views/post/deletepost.blade.php
@extends('admin.master')
@section('content')
@section('Judul-Page','Keranjang Sampah [Postingan]')


@if(Session::has('success'))
<div class="alert alert-success" role="alert">
   {{Session('success')}}
   </div>
@endif

<table class="table table-striped table-hover table-sm table-bordered table-da">
  <thead>
    <tr>
      <th>No</th>
      <th>Judul</th>
      <th>Category</th>
      <th>Tags</th>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($postdelete as $result => $hasil)
    <tr>
      <td>{{$result+$postdelete->firstitem()}}</td>
      <td>{{$hasil->judul}}</td>
      <td>{{$hasil->category->nama}}</td>
      <td>@foreach ($hasil->tags as $tag)
        <a href="" class="btn btn-success btn-sm">{{$tag->nama}}</a>
          @endforeach
      </td>
      <td><img src="{{asset($hasil->gambar)}}" alt="" class="img-fluid" style="width:80px"></td></td>
      <td>
          <form action="{{route('post.kill', $hasil->id)}}" method="POST">
              @csrf
              @method('delete')
              <a href="{{route('post.restore',$hasil->id)}}" class="btn btn-info">Restore</a>
              <button type="submit" class=" btn btn-danger">Delete</button>
          </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>

{{ $postdelete->links() }}
@endsection

resources/views/post/editpost.blade.php
@extends('admin.master ')
@section('Judul-Page','Edit Postingan')
@section('content')

  @if(count($errors)>0)
  	@foreach($errors->all() as $error)
  	<div class="alert alert-danger" role="alert">
      {{ $error }}
	</div>
  	@endforeach
  @endif

  @if(Session::has('success'))
  	<div class="alert alert-success" role="alert">
      {{ Session('success') }}
	</div>

  @endif


<form action="{{route('post.update', $post->id)}}" method="POST" enctype="multipart/form-data">
@csrf
@method('PATCH')

  <div class="form-group">
      <label>Judul</label>
      <input type="text" class="form-control" name="judul" value="{{ $post->judul }}">
  </div>


  <div class="form-group">
      <label>Kategori</label>
      <select class="form-control" name="category_id">
          <option value="">Pilih Kategori</option>

      	@foreach($category as $kategori)
      	<option value="{{ $kategori->id }}"
            @if($kategori->id == $post->category_id)
            selected
      	    @endif
      		>{{  $kategori->nama }}</option>
      	@endforeach
      </select>
  </div>
  <div class="form-group">
      <label>Pilih Tags</label>
      <select class="form-control select2" multiple="" name="tags[]">
          @foreach($tags as $tag)
          <option value="{{ $tag->id }}"
          @foreach($post->tags as $value)
          	@if($tag->id == $value->id)
          	selected
          	@endif
          @endforeach
          	>{{ $tag->nama }}</option>
          @endforeach
      </select>
  </div>
  <div class="form-group">
      <label>Konten</label>
      <textarea class="form-control" name="content" id="content">{{ $post->content }}</textarea>
  </div>
  <div class="form-group">
      <label>Thumbnail</label>
      <input type="file" name="gambar" class="form-control">
  </div>

  <div class="form-group">
      <button class="btn btn-primary btn-block">Update Postingan</button>
  </div>

  </form>

@endsection

resources/views/post/index.blade.php
@extends('admin.master')
@section('content')
@section('Judul-Page','POSTINGAN')


@if(Session::has('success'))
<div class="alert alert-success" role="alert">
   {{Session('success')}}
   </div>
@endif

<a href="{{route('post.create')}}" class="btn btn-info btn-sm">Tambah POST</a>
<table class="table tablle-striped table-hover table-sm table-bordered table-da">
  <thead>
    <tr>
      <th>No</th>
      <th>Judul</th>
      <th>Category</th>
      <th>Tags</th>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($post as $result => $hasil)
    <tr>
      <td>{{$result+$post->firstitem()}}</td>
      <td>{{$hasil->judul}}</td>
      <td>{{$hasil->category->nama}}</td>
      <td>@foreach ($hasil->tags as $tag)
        <a href="" class="btn btn-success btn-sm">{{$tag->nama}}</a>
          @endforeach
      </td>
      <td><img src="{{asset($hasil->gambar)}}" alt="" class="img-fluid" style="width:80px"></td></td>
      <td>
          <form action="{{route('post.destroy', $hasil->id)}}" method="POST">
              @csrf
              @method('delete')
              <a href="{{ route('post.edit', $hasil->id)}}" class="btn btn-primary fas fa-pen"></a>
          <button type="submit" class=" btn btn-danger fas fa-trash"></button>
          </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>

{{ $post->links() }}
@endsection