routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\PostController;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/category', 'CategoryController');
Route::resource('/tag', 'TagController');
Route::get('/post/hapus', 'PostController@list_postdelete')->name('list_postdelete');
Route::get('/post/restore{id} ', 'PostController@restore')->name('post.restore');
route::delete('/post/Kill{id}', 'PostController@kill')->name('post.kill');
Route::resource('post','PostController');

Route::get('/dashboard', function(){
    return view('admin.master');
})->name('dashboard');

app/Tags.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    protected $fillable = ['nama','slug'];

    public  function posts(){
        return $this->belongsToMany('App\Posts');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;
use App\Tags;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tag = Tags::paginate(10);
        return view('tag.index',compact('tag'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //menambahkan validasi nama -> wajib min.3 karakter
        $this->validate($request,[
            'nama' => 'required|min:3'
        ]);
        Tags::create([
            'nama' => $request->nama,
            'slug' => Str::slug($request->nama)
        ]);
        return redirect()->back()->with('success','Data berhasil  disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $tag = Tags::findorfail($id);
        return view('tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama' => 'required'
        ]);
        $tag_data = [
        'nama' => $request->nama,
        'slug' => Str::slug($request->nama)
        ];
        Tags::whereId($id)->update($tag_data);
        return redirect()->route('tag.index')->with('success','Tag berhasil  diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $tag = Tags::findorfail($id);
        $tag->delete();
        return  redirect()->back()->with('success','Tag berhasil dihapus');
    }
}

resources/views/tag/create.blade.php
@extends('admin.master')
@section('content')
@section('Judul-Page','Create Data')

@if (count($errors)>0)
    @foreach($errors->all() as $error)
    <div class="alert alert-danger" role="alert">
    {{$error}}
    </div>
    @endforeach
@endif

@if(Session::has('success'))
<div class="alert alert-success" role="alert">
   {{Session('success')}}
   </div>
@endif
<form action="{{route('tag.store')}}" method="POST">
@csrf
<div class="form-group">
    <label for="">Kategori</label>
    <input type="text" class="form-control" name="nama">
</div>
<div class="form-group">
    <button class="btn btn-primary btn-block">SIMPAN</button>
</div>
</form>

<a href="{{route('tag.index')}}" class="btn btn-success">Kembali</a>
@endsection

resources/views/tag/edit.blade.php
@extends('admin.master')
@section('content')
@section('Judul-Page','Edit tag')

@if (count($errors)>0)
    @foreach($errors->all() as $error)
    <div class="alert alert-danger" role="alert">
    {{$error}}
    </div>
    @endforeach
@endif

@if(Session::has('success'))
<div class="alert alert-success" role="alert">
   {{Session('success')}}
   </div>
@endif
<form action="{{route('tag.update', $tag->id)}}" method="POST">
@csrf
@method('patch')
<div class="form-group">
    <label for="">Tag</label>
    <input type="text" class="form-control" name="nama" value="{{$tag->nama}}">
</div>
<div class="form-group">
    <button class="btn btn-primary btn-block">UPDATE Tags</button>
</div>
</form>

<a href="{{route('tag.index')}}" class="btn btn-success">Kembali</a>
@endsection

resources/views/tag/index.blade.php
@extends('admin.master')
@section('content')
@section('Judul-Page','Tag')


@if(Session::has('success'))
<div class="alert alert-success" role="alert">
   {{Session('success')}}
   </div>
@endif

<a href="{{route('tag.create')}}" class="btn btn-info btn-sm">Tambah Tag</a>
<table class="table tablle-striped table-hover table-sm table-bordered table-da">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nama</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($tag as $result => $hasil)
    <tr>
      <td>{{$result+$tag->firstitem()}}</td>
      <td>{{$hasil->nama}}</td>
      <td>
          <form action="{{route('tag.destroy', $hasil->id)}}" method="POST">
              @csrf
              @method('delete')
              <a href="{{ route('tag.edit', $hasil->id)}}" class="btn btn-primary">Edit</a>
          <button type="submit" class="btn btn-danger">Delete</button>
          </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
{{ $tag->links() }}
@endsection